public class CommercialDriverBuilder {
    public string FirstName {get;set;}
    public string LastName {get;set;}
    public string DateofBirth {get;set;}
    public string Gender {get;set;}
    public string MaritalStatus {get;set;}
    public string TypeOfLicense {get;set;}
    public string LicenseState {get;set;}
    public string LicenseNumber {get;set;}
    public string AgeFirstLicensed {get;set;}
    public string NumberofAccident {get;set;}
    public string NumberofViolation {get;set;}
    public string DutiesofDriver {get;set;}
    public string HireDate {get;set;}

}