/*
** LWC Generated by vlocity-lwc-generator.herokuapp.com
** Developer: Kirk Leibert
** Date: 6-14-2020
*/ 

import { LightningElement,track,api } from 'lwc';
    import { OmniscriptBaseMixin } from 'vlocity_ins/omniscriptBaseMixin';
    export default class statesSelection extends OmniscriptBaseMixin(LightningElement) {  
    //@track data = {};
    @track displayRows = [];
    @api title = '';
    @api multiselect;

    @track 
    source_data = [];

    @api
    get source() {
        return this.source_data;
    }
    set source(val) {
        //  Note that we get null if there data is not yet present in the OS
        if (val === null) {
           console.log("Got null source data");
            return    
        }
        this.source_data = val;        
        this.initMethod();
    }

    connectedCallback() {
        console.log('connectedCallback');
        this.initMethod();
    }

    renderedCallback() {
        console.log('renderedCallback');
    }
   
    initMethod() {
        let tempRows = [];
        tempRows = JSON.parse(JSON.stringify(this.source_data));
        
        if (tempRows.length == 0) {
            console.log("source data is null - look for data in data.json node with same name as Custom LWC element");
            tempRows = JSON.parse(JSON.stringify(this.omniJsonData[this.omniJsonDef.name]));
        }
        
        tempRows.forEach((item, i) => {
           item.tagname = "cb_" + i;
           item.rowid = i;
           item.checked = false;
           item.filtered = false;
        });

        this.displayRows = [];
        tempRows.forEach((item, i) => {
            this.displayRows.push(item);
        });    
   }

    filterSelectedFromList(list) {
        const filteredList = list.filter(
            checked = true
        );
        return filteredList
    }

    selectRow(event) {        
        const selected = event.target.checked;
        const target = event.target.name;
        const iteration=parseInt(target.substring(3,target.length));
        this.displayRows[iteration].checked = selected;
    }

    getRows() {
        let data = [];
        let filtered = [];
        data = this.displayRows;
        filtered = data.filter(function(item){
            return item.checked == true;
        });
        return filtered;
    }

    handleSelection(event) {
        this.selectRow(event);
        this.omniUpdateDataJson(this.getRows());
    }
}