public class CommercialVehicleBuilder {
    public string VehicleType {get;set;}
    public string Year {get;set;}
    public string Make {get;set;}
    public string Model {get;set;}
    public string Trim {get;set;}
    public string BodyType {get;set;}
    public string OwenershipType {get;set;}
    public string Color {get;set;}
    public string VIN {get;set;}
    public string LicenseState {get;set;}
    public string LicensePlate {get;set;}
    public string GaragePostalCode {get;set;}
    public string AnnualMilage {get;set;}
    public string RadiusofOperation {get;set;}
    public string Condition {get;set;}
}